// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siutuluklbvjgxlvroak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdXR1bHVrbGJ2amd4bHZyb2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjMwODQsImV4cCI6MjA2NTUzOTA4NH0.C4447-oIQm4fgZQmVHsIsXndJbZHK6Cjq6bi_ryFdy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);